variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure Pass - Sponsorship (8aa2cc15-1b23-4f6a-916c-fd3a56f63652)'
    appType: 'webApp'
    appName: 'demoappaz40038'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'